// <auto-generated/>

namespace Konesans.Dts.ExpressionEditor
{
    using System;
    using System.Drawing;
    using System.Windows.Forms;
    using Konesans.Dts.ExpressionEditor.Controls;

    partial class ExpressionEditorPublic
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes of the resources (other than memory) used by the <see cref="T:System.Windows.Forms.Form"/>.
        /// </summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.OK = new System.Windows.Forms.Button();
            this.Cancel = new System.Windows.Forms.Button();
            this.labelFormTitle = new System.Windows.Forms.Label();
            this.Remove = new System.Windows.Forms.Button();
            this.line3D1 = new Konesans.Dts.ExpressionEditor.Controls.Line3D();
            this.expressionEditorView = new Konesans.Dts.ExpressionEditor.Controls.ExpressionEditorView();
            this.SuspendLayout();
            // 
            // OK
            // 
            this.OK.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.OK.Location = new System.Drawing.Point(464, 335);
            this.OK.Name = "OK";
            this.OK.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.OK.Size = new System.Drawing.Size(76, 24);
            this.OK.TabIndex = 6;
            this.OK.Text = "OK";
            this.OK.Click += new System.EventHandler(this.OK_Click);
            // 
            // Cancel
            // 
            this.Cancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.Cancel.Location = new System.Drawing.Point(546, 335);
            this.Cancel.Name = "Cancel";
            this.Cancel.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.Cancel.Size = new System.Drawing.Size(76, 24);
            this.Cancel.TabIndex = 7;
            this.Cancel.Text = "Cancel";
            this.Cancel.Click += new System.EventHandler(this.Cancel_Click);
            // 
            // labelFormTitle
            // 
            this.labelFormTitle.AutoSize = true;
            this.labelFormTitle.Location = new System.Drawing.Point(12, 9);
            this.labelFormTitle.Name = "labelFormTitle";
            this.labelFormTitle.Size = new System.Drawing.Size(117, 13);
            this.labelFormTitle.TabIndex = 7;
            this.labelFormTitle.Text = "Expression for property:";
            // 
            // Remove
            // 
            this.Remove.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.Remove.Location = new System.Drawing.Point(12, 334);
            this.Remove.Name = "Remove";
            this.Remove.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.Remove.Size = new System.Drawing.Size(76, 24);
            this.Remove.TabIndex = 8;
            this.Remove.Text = "Remove";
            this.Remove.Click += new System.EventHandler(this.Remove_Click);
            // 
            // line3D1
            // 
            this.line3D1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.line3D1.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.line3D1.Location = new System.Drawing.Point(10, 322);
            this.line3D1.MaximumSize = new System.Drawing.Size(12400, 2);
            this.line3D1.MinimumSize = new System.Drawing.Size(4, 2);
            this.line3D1.Name = "line3D1";
            this.line3D1.Size = new System.Drawing.Size(612, 2);
            this.line3D1.TabIndex = 5;
            // 
            // expressionEditorView
            // 
            this.expressionEditorView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.expressionEditorView.ApplicationTitle = "Expression Editor";
            this.expressionEditorView.EditMode = false;
            this.expressionEditorView.Expression = "";
            this.expressionEditorView.ExpressionColor = System.Drawing.SystemColors.WindowText;
            this.expressionEditorView.ExpressionFont = new System.Drawing.Font("Tahoma", 8F);
            this.expressionEditorView.FindOrReplaceMatchCase = false;
            this.expressionEditorView.FindOrReplaceSearchUp = false;
            this.expressionEditorView.Location = new System.Drawing.Point(10, 25);
            this.expressionEditorView.MinimumSize = new System.Drawing.Size(338, 121);
            this.expressionEditorView.Name = "expressionEditorView";
            this.expressionEditorView.ResultColor = System.Drawing.SystemColors.WindowText;
            this.expressionEditorView.ResultFont = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.expressionEditorView.ResultType = System.TypeCode.Empty;
            this.expressionEditorView.ResultTypeValidate = true;
            this.expressionEditorView.Saved = false;
            this.expressionEditorView.Size = new System.Drawing.Size(612, 291);
            this.expressionEditorView.SplitterDistanceExpressions = 233;
            this.expressionEditorView.SplitterDistanceMain = 215;
            this.expressionEditorView.SplitterDistanceResult = 82;
            this.expressionEditorView.TabIndex = 9;
            this.expressionEditorView.WordWrap = true;
            // 
            // ExpressionEditorPublic
            // 
            this.ClientSize = new System.Drawing.Size(634, 369);
            this.Controls.Add(this.expressionEditorView);
            this.Controls.Add(this.Remove);
            this.Controls.Add(this.labelFormTitle);
            this.Controls.Add(this.line3D1);
            this.Controls.Add(this.OK);
            this.Controls.Add(this.Cancel);
            this.KeyPreview = true;
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(338, 121);
            this.Name = "ExpressionEditorPublic";
            this.ShowInTaskbar = false;
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Expression Editor";
            this.KeyUp += new System.Windows.Forms.KeyEventHandler(this.ExpressionEditor_KeyUp);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button OK;
        private System.Windows.Forms.Button Cancel;
        private Line3D line3D1;
        private System.Windows.Forms.Label labelFormTitle;
        private System.Windows.Forms.Button Remove;
    }
}