// <auto-generated/>

namespace Konesans.Dts.ExpressionEditor
{
    using System;
    using System.Drawing;
    using System.Windows.Forms;
    using Konesans.Dts.ExpressionEditor.Controls;

    partial class ExpressionEditorPublic
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes of the resources (other than memory) used by the <see cref="T:System.Windows.Forms.Form"/>.
        /// </summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.OK = new System.Windows.Forms.Button();
            this.Cancel = new System.Windows.Forms.Button();
            this.Remove = new System.Windows.Forms.Button();
            this.toolStrip = new System.Windows.Forms.ToolStrip();
            this.TitlePanel = new System.Windows.Forms.Panel();
            this.TitleLabel = new System.Windows.Forms.Label();
            this.TitleValueLabel = new System.Windows.Forms.Label();
            this.line3DTop = new Konesans.Dts.ExpressionEditor.Controls.Line3D();
            this.expressionEditorView = new Konesans.Dts.ExpressionEditor.Controls.ExpressionEditorView();
            this.lineBottom = new Konesans.Dts.ExpressionEditor.Controls.Line3D();
            this.TitlePanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // OK
            // 
            this.OK.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.OK.Location = new System.Drawing.Point(606, 492);
            this.OK.Name = "OK";
            this.OK.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.OK.Size = new System.Drawing.Size(76, 24);
            this.OK.TabIndex = 6;
            this.OK.Text = "&OK";
            this.OK.Click += new System.EventHandler(this.OK_Click);
            // 
            // Cancel
            // 
            this.Cancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.Cancel.Location = new System.Drawing.Point(688, 492);
            this.Cancel.Name = "Cancel";
            this.Cancel.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.Cancel.Size = new System.Drawing.Size(76, 24);
            this.Cancel.TabIndex = 7;
            this.Cancel.Text = "&Cancel";
            this.Cancel.Click += new System.EventHandler(this.Cancel_Click);
            // 
            // Remove
            // 
            this.Remove.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.Remove.Location = new System.Drawing.Point(12, 491);
            this.Remove.Name = "Remove";
            this.Remove.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.Remove.Size = new System.Drawing.Size(76, 24);
            this.Remove.TabIndex = 8;
            this.Remove.Text = "&Remove";
            this.Remove.Click += new System.EventHandler(this.Remove_Click);
            // 
            // toolStrip
            // 
            this.toolStrip.Location = new System.Drawing.Point(0, 0);
            this.toolStrip.Name = "toolStrip";
            this.toolStrip.Size = new System.Drawing.Size(776, 25);
            this.toolStrip.TabIndex = 10;
            this.toolStrip.Text = "Form ToolStrip";
            // 
            // TitlePanel
            // 
            this.TitlePanel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.TitlePanel.Controls.Add(this.TitleValueLabel);
            this.TitlePanel.Controls.Add(this.TitleLabel);
            this.TitlePanel.Location = new System.Drawing.Point(9, 34);
            this.TitlePanel.Name = "TitlePanel";
            this.TitlePanel.Size = new System.Drawing.Size(755, 16);
            this.TitlePanel.TabIndex = 11;
            // 
            // TitleLabel
            // 
            this.TitleLabel.AutoSize = true;
            this.TitleLabel.Dock = System.Windows.Forms.DockStyle.Left;
            this.TitleLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TitleLabel.Location = new System.Drawing.Point(0, 0);
            this.TitleLabel.Name = "TitleLabel";
            this.TitleLabel.Size = new System.Drawing.Size(141, 13);
            this.TitleLabel.TabIndex = 0;
            this.TitleLabel.Text = "Expression for property:";
            this.TitleLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // TitleValueLabel
            // 
            this.TitleValueLabel.AutoSize = true;
            this.TitleValueLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TitleValueLabel.Location = new System.Drawing.Point(141, 0);
            this.TitleValueLabel.Name = "TitleValueLabel";
            this.TitleValueLabel.Size = new System.Drawing.Size(67, 13);
            this.TitleValueLabel.TabIndex = 1;
            this.TitleValueLabel.Text = "Value (Type)";
            this.TitleValueLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // line3DTop
            // 
            this.line3DTop.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.line3DTop.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.line3DTop.Location = new System.Drawing.Point(0, 26);
            this.line3DTop.MaximumSize = new System.Drawing.Size(12400, 2);
            this.line3DTop.MinimumSize = new System.Drawing.Size(4, 2);
            this.line3DTop.Name = "line3DTop";
            this.line3DTop.Size = new System.Drawing.Size(784, 2);
            this.line3DTop.TabIndex = 12;
            // 
            // expressionEditorView
            // 
            this.expressionEditorView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.expressionEditorView.ApplicationTitle = "Expression Editor";
            this.expressionEditorView.EditMode = false;
            this.expressionEditorView.Expression = "";
            this.expressionEditorView.ExpressionColor = System.Drawing.SystemColors.WindowText;
            this.expressionEditorView.ExpressionFont = new System.Drawing.Font("Tahoma", 8F);
            this.expressionEditorView.FindOrReplaceMatchCase = false;
            this.expressionEditorView.FindOrReplaceSearchUp = false;
            this.expressionEditorView.Location = new System.Drawing.Point(10, 49);
            this.expressionEditorView.MinimumSize = new System.Drawing.Size(338, 121);
            this.expressionEditorView.Name = "expressionEditorView";
            this.expressionEditorView.ResultColor = System.Drawing.SystemColors.WindowText;
            this.expressionEditorView.ResultFont = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.expressionEditorView.ResultType = System.TypeCode.Empty;
            this.expressionEditorView.ResultTypeValidate = true;
            this.expressionEditorView.Saved = false;
            this.expressionEditorView.Size = new System.Drawing.Size(754, 423);
            this.expressionEditorView.SplitterDistanceExpressions = 230;
            this.expressionEditorView.SplitterDistanceMain = 350;
            this.expressionEditorView.SplitterDistanceResult = 198;
            this.expressionEditorView.TabIndex = 9;
            this.expressionEditorView.WordWrap = true;
            // 
            // lineBottom
            // 
            this.lineBottom.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.lineBottom.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.lineBottom.Location = new System.Drawing.Point(10, 479);
            this.lineBottom.MaximumSize = new System.Drawing.Size(12400, 2);
            this.lineBottom.MinimumSize = new System.Drawing.Size(4, 2);
            this.lineBottom.Name = "lineBottom";
            this.lineBottom.Size = new System.Drawing.Size(754, 2);
            this.lineBottom.TabIndex = 5;
            // 
            // ExpressionEditorPublic
            // 
            this.AcceptButton = this.OK;
            this.CancelButton = this.Cancel;
            this.ClientSize = new System.Drawing.Size(776, 526);
            this.Controls.Add(this.line3DTop);
            this.Controls.Add(this.TitlePanel);
            this.Controls.Add(this.expressionEditorView);
            this.Controls.Add(this.Remove);
            this.Controls.Add(this.lineBottom);
            this.Controls.Add(this.OK);
            this.Controls.Add(this.Cancel);
            this.Controls.Add(this.toolStrip);
            this.KeyPreview = true;
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(338, 121);
            this.Name = "ExpressionEditorPublic";
            this.ShowInTaskbar = false;
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Expression Editor";
            this.KeyUp += new System.Windows.Forms.KeyEventHandler(this.ExpressionEditor_KeyUp);
            this.TitlePanel.ResumeLayout(false);
            this.TitlePanel.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button OK;
        private System.Windows.Forms.Button Cancel;
        private Line3D lineBottom;
        private System.Windows.Forms.Button Remove;
        private ToolStrip toolStrip;
        private Panel TitlePanel;
        private Label TitleLabel;
        private Label TitleValueLabel;
        private Line3D line3DTop;
    }
}