// <auto-generated/>

using System.ComponentModel;
using System.Windows.Forms;
using Konesans.Dts.ExpressionEditor.Controls;

namespace Konesans.Dts.Tools.ExpressionTester
{
    partial class Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
            this.recentFilesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.recentExpressionFilesPlaceHolderStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.menuStrip = new System.Windows.Forms.MenuStrip();
            this.fileMenu = new System.Windows.Forms.ToolStripMenuItem();
            this.newToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.openToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator9 = new System.Windows.Forms.ToolStripSeparator();
            this.saveToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveAsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator16 = new System.Windows.Forms.ToolStripSeparator();
            this.saveAsTemplateToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator4 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripSeparator5 = new System.Windows.Forms.ToolStripSeparator();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editMenu = new System.Windows.Forms.ToolStripMenuItem();
            this.undoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.redoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator6 = new System.Windows.Forms.ToolStripSeparator();
            this.cutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.copyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.pasteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator3 = new System.Windows.Forms.ToolStripSeparator();
            this.findToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.replaceToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator7 = new System.Windows.Forms.ToolStripSeparator();
            this.selectAllToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.viewMenu = new System.Windows.Forms.ToolStripMenuItem();
            this.toolBarToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.statusBarToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.wordWrapToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editFunctionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.expressionsMenu = new System.Windows.Forms.ToolStripMenuItem();
            this.evaluateToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator12 = new System.Windows.Forms.ToolStripSeparator();
            this.addVariableToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editVariableToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.deleteVariableToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator13 = new System.Windows.Forms.ToolStripSeparator();
            this.expressionFilePropertiesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolsMenu = new System.Windows.Forms.ToolStripMenuItem();
            this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpMenu = new System.Windows.Forms.ToolStripMenuItem();
            this.searchToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator8 = new System.Windows.Forms.ToolStripSeparator();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStrip = new System.Windows.Forms.ToolStrip();
            this.newToolStripButton = new System.Windows.Forms.ToolStripButton();
            this.openToolStripButton = new System.Windows.Forms.ToolStripButton();
            this.saveToolStripButton = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparatorEndFile = new System.Windows.Forms.ToolStripSeparator();
            this.optionsToolStripButton = new System.Windows.Forms.ToolStripButton();
            this.expressionFileSettingsToolStripButton = new System.Windows.Forms.ToolStripButton();
            this.statusStrip = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabelFilename = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabelResultType = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabelLine = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabelColumn = new System.Windows.Forms.ToolStripStatusLabel();
            this.expressionEditor = new Konesans.Dts.ExpressionEditor.Controls.ExpressionEditorView();
            this.menuStrip.SuspendLayout();
            this.toolStrip.SuspendLayout();
            this.statusStrip.SuspendLayout();
            this.SuspendLayout();
            // 
            // recentFilesToolStripMenuItem
            // 
            this.recentFilesToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.recentExpressionFilesPlaceHolderStripMenuItem});
            this.recentFilesToolStripMenuItem.Name = "recentFilesToolStripMenuItem";
            this.recentFilesToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.recentFilesToolStripMenuItem.Text = "Recent Files";
            this.recentFilesToolStripMenuItem.DropDownOpening += new System.EventHandler(this.RecentExpressionFileToolStripMenuItem_DropDownOpening);
            // 
            // recentExpressionFilesPlaceHolderStripMenuItem
            // 
            this.recentExpressionFilesPlaceHolderStripMenuItem.Enabled = false;
            this.recentExpressionFilesPlaceHolderStripMenuItem.Name = "recentExpressionFilesPlaceHolderStripMenuItem";
            this.recentExpressionFilesPlaceHolderStripMenuItem.Size = new System.Drawing.Size(174, 22);
            this.recentExpressionFilesPlaceHolderStripMenuItem.Text = "No recent files found";
            // 
            // menuStrip
            // 
            this.menuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileMenu,
            this.editMenu,
            this.viewMenu,
            this.expressionsMenu,
            this.toolsMenu,
            this.helpMenu});
            this.menuStrip.Location = new System.Drawing.Point(0, 0);
            this.menuStrip.Name = "menuStrip";
            this.menuStrip.Size = new System.Drawing.Size(782, 24);
            this.menuStrip.TabIndex = 0;
            this.menuStrip.Text = "MenuStrip";
            // 
            // fileMenu
            // 
            this.fileMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.newToolStripMenuItem,
            this.openToolStripMenuItem,
            this.toolStripSeparator9,
            this.saveToolStripMenuItem,
            this.saveAsToolStripMenuItem,
            this.toolStripSeparator16,
            this.saveAsTemplateToolStripMenuItem,
            this.toolStripSeparator4,
            this.recentFilesToolStripMenuItem,
            this.toolStripSeparator5,
            this.exitToolStripMenuItem});
            this.fileMenu.ImageTransparentColor = System.Drawing.SystemColors.ActiveBorder;
            this.fileMenu.Name = "fileMenu";
            this.fileMenu.Size = new System.Drawing.Size(35, 20);
            this.fileMenu.Text = "&File";
            // 
            // newToolStripMenuItem
            // 
            this.newToolStripMenuItem.Image = global::Konesans.Dts.Tools.ExpressionTester.Properties.Resources.NewDocument;
            this.newToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.newToolStripMenuItem.Name = "newToolStripMenuItem";
            this.newToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N)));
            this.newToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.newToolStripMenuItem.Text = "&New";
            this.newToolStripMenuItem.Click += new System.EventHandler(this.New);
            // 
            // openToolStripMenuItem
            // 
            this.openToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("openToolStripMenuItem.Image")));
            this.openToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.openToolStripMenuItem.Name = "openToolStripMenuItem";
            this.openToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.O)));
            this.openToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.openToolStripMenuItem.Text = "&Open";
            this.openToolStripMenuItem.Click += new System.EventHandler(this.OpenFile);
            // 
            // toolStripSeparator9
            // 
            this.toolStripSeparator9.Name = "toolStripSeparator9";
            this.toolStripSeparator9.Size = new System.Drawing.Size(157, 6);
            // 
            // saveToolStripMenuItem
            // 
            this.saveToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("saveToolStripMenuItem.Image")));
            this.saveToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.saveToolStripMenuItem.Name = "saveToolStripMenuItem";
            this.saveToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.S)));
            this.saveToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.saveToolStripMenuItem.Text = "&Save";
            this.saveToolStripMenuItem.Click += new System.EventHandler(this.SaveFile);
            // 
            // saveAsToolStripMenuItem
            // 
            this.saveAsToolStripMenuItem.Name = "saveAsToolStripMenuItem";
            this.saveAsToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.saveAsToolStripMenuItem.Text = "Save &As";
            this.saveAsToolStripMenuItem.Click += new System.EventHandler(this.SaveFileAs);
            // 
            // toolStripSeparator16
            // 
            this.toolStripSeparator16.Name = "toolStripSeparator16";
            this.toolStripSeparator16.Size = new System.Drawing.Size(157, 6);
            // 
            // saveAsTemplateToolStripMenuItem
            // 
            this.saveAsTemplateToolStripMenuItem.Name = "saveAsTemplateToolStripMenuItem";
            this.saveAsTemplateToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.saveAsTemplateToolStripMenuItem.Text = "Save As Template";
            this.saveAsTemplateToolStripMenuItem.Click += new System.EventHandler(this.SaveAsTemplateToolStripMenuItem_Click);
            // 
            // toolStripSeparator4
            // 
            this.toolStripSeparator4.Name = "toolStripSeparator4";
            this.toolStripSeparator4.Size = new System.Drawing.Size(157, 6);
            // 
            // toolStripSeparator5
            // 
            this.toolStripSeparator5.Name = "toolStripSeparator5";
            this.toolStripSeparator5.Size = new System.Drawing.Size(157, 6);
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.exitToolStripMenuItem.Text = "E&xit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.ExitToolsStripMenuItem_Click);
            // 
            // editMenu
            // 
            this.editMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.undoToolStripMenuItem,
            this.redoToolStripMenuItem,
            this.toolStripSeparator6,
            this.cutToolStripMenuItem,
            this.copyToolStripMenuItem,
            this.pasteToolStripMenuItem,
            this.toolStripSeparator3,
            this.findToolStripMenuItem,
            this.replaceToolStripMenuItem,
            this.toolStripSeparator7,
            this.selectAllToolStripMenuItem});
            this.editMenu.Name = "editMenu";
            this.editMenu.Size = new System.Drawing.Size(37, 20);
            this.editMenu.Text = "&Edit";
            // 
            // undoToolStripMenuItem
            // 
            this.undoToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("undoToolStripMenuItem.Image")));
            this.undoToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.undoToolStripMenuItem.Name = "undoToolStripMenuItem";
            this.undoToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Z)));
            this.undoToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.undoToolStripMenuItem.Text = "&Undo";
            this.undoToolStripMenuItem.Click += new System.EventHandler(this.Undo);
            // 
            // redoToolStripMenuItem
            // 
            this.redoToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("redoToolStripMenuItem.Image")));
            this.redoToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.redoToolStripMenuItem.Name = "redoToolStripMenuItem";
            this.redoToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Y)));
            this.redoToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.redoToolStripMenuItem.Text = "&Redo";
            this.redoToolStripMenuItem.Click += new System.EventHandler(this.Redo);
            // 
            // toolStripSeparator6
            // 
            this.toolStripSeparator6.Name = "toolStripSeparator6";
            this.toolStripSeparator6.Size = new System.Drawing.Size(153, 6);
            // 
            // cutToolStripMenuItem
            // 
            this.cutToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("cutToolStripMenuItem.Image")));
            this.cutToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.cutToolStripMenuItem.Name = "cutToolStripMenuItem";
            this.cutToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.X)));
            this.cutToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.cutToolStripMenuItem.Text = "Cu&t";
            this.cutToolStripMenuItem.Click += new System.EventHandler(this.Cut);
            // 
            // copyToolStripMenuItem
            // 
            this.copyToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("copyToolStripMenuItem.Image")));
            this.copyToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.copyToolStripMenuItem.Name = "copyToolStripMenuItem";
            this.copyToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.C)));
            this.copyToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.copyToolStripMenuItem.Text = "&Copy";
            this.copyToolStripMenuItem.Click += new System.EventHandler(this.Copy);
            // 
            // pasteToolStripMenuItem
            // 
            this.pasteToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("pasteToolStripMenuItem.Image")));
            this.pasteToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.pasteToolStripMenuItem.Name = "pasteToolStripMenuItem";
            this.pasteToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.V)));
            this.pasteToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.pasteToolStripMenuItem.Text = "&Paste";
            this.pasteToolStripMenuItem.Click += new System.EventHandler(this.Paste);
            // 
            // toolStripSeparator3
            // 
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new System.Drawing.Size(153, 6);
            // 
            // findToolStripMenuItem
            // 
            this.findToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("findToolStripMenuItem.Image")));
            this.findToolStripMenuItem.Name = "findToolStripMenuItem";
            this.findToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.F)));
            this.findToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.findToolStripMenuItem.Text = "&Find";
            this.findToolStripMenuItem.Click += new System.EventHandler(this.FindExpression);
            // 
            // replaceToolStripMenuItem
            // 
            this.replaceToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("replaceToolStripMenuItem.Image")));
            this.replaceToolStripMenuItem.Name = "replaceToolStripMenuItem";
            this.replaceToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.H)));
            this.replaceToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.replaceToolStripMenuItem.Text = "R&eplace";
            this.replaceToolStripMenuItem.Click += new System.EventHandler(this.ReplaceExpression);
            // 
            // toolStripSeparator7
            // 
            this.toolStripSeparator7.Name = "toolStripSeparator7";
            this.toolStripSeparator7.Size = new System.Drawing.Size(153, 6);
            // 
            // selectAllToolStripMenuItem
            // 
            this.selectAllToolStripMenuItem.Name = "selectAllToolStripMenuItem";
            this.selectAllToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.A)));
            this.selectAllToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.selectAllToolStripMenuItem.Text = "Select &All";
            this.selectAllToolStripMenuItem.Click += new System.EventHandler(this.SelectAllText);
            // 
            // viewMenu
            // 
            this.viewMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolBarToolStripMenuItem,
            this.statusBarToolStripMenuItem,
            this.wordWrapToolStripMenuItem,
            this.editFunctionsToolStripMenuItem});
            this.viewMenu.Name = "viewMenu";
            this.viewMenu.Size = new System.Drawing.Size(41, 20);
            this.viewMenu.Text = "&View";
            this.viewMenu.DropDownOpening += new System.EventHandler(this.ViewMenu_DropDownOpening);
            // 
            // toolBarToolStripMenuItem
            // 
            this.toolBarToolStripMenuItem.Checked = true;
            this.toolBarToolStripMenuItem.CheckOnClick = true;
            this.toolBarToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.toolBarToolStripMenuItem.Name = "toolBarToolStripMenuItem";
            this.toolBarToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
            this.toolBarToolStripMenuItem.Text = "&Toolbar";
            this.toolBarToolStripMenuItem.Click += new System.EventHandler(this.ToolBarToolStripMenuItem_Click);
            // 
            // statusBarToolStripMenuItem
            // 
            this.statusBarToolStripMenuItem.Checked = true;
            this.statusBarToolStripMenuItem.CheckOnClick = true;
            this.statusBarToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.statusBarToolStripMenuItem.Name = "statusBarToolStripMenuItem";
            this.statusBarToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
            this.statusBarToolStripMenuItem.Text = "&Status Bar";
            this.statusBarToolStripMenuItem.Click += new System.EventHandler(this.StatusBarToolStripMenuItem_Click);
            // 
            // wordWrapToolStripMenuItem
            // 
            this.wordWrapToolStripMenuItem.Checked = true;
            this.wordWrapToolStripMenuItem.CheckOnClick = true;
            this.wordWrapToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.wordWrapToolStripMenuItem.Name = "wordWrapToolStripMenuItem";
            this.wordWrapToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
            this.wordWrapToolStripMenuItem.Text = "Word Wrap";
            this.wordWrapToolStripMenuItem.Click += new System.EventHandler(this.WordWrapToolStripMenuItem_Click);
            // 
            // editFunctionsToolStripMenuItem
            // 
            this.editFunctionsToolStripMenuItem.CheckOnClick = true;
            this.editFunctionsToolStripMenuItem.Name = "editFunctionsToolStripMenuItem";
            this.editFunctionsToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
            this.editFunctionsToolStripMenuItem.Text = "Edit Functions";
            this.editFunctionsToolStripMenuItem.Click += new System.EventHandler(this.EditFunctionsToolStripMenuItem_Click);
            // 
            // expressionsMenu
            // 
            this.expressionsMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.evaluateToolStripMenuItem,
            this.toolStripSeparator12,
            this.addVariableToolStripMenuItem,
            this.editVariableToolStripMenuItem,
            this.deleteVariableToolStripMenuItem,
            this.toolStripSeparator13,
            this.expressionFilePropertiesToolStripMenuItem});
            this.expressionsMenu.Name = "expressionsMenu";
            this.expressionsMenu.Size = new System.Drawing.Size(71, 20);
            this.expressionsMenu.Text = "Expression";
            // 
            // evaluateToolStripMenuItem
            // 
            this.evaluateToolStripMenuItem.Image = global::Konesans.Dts.Tools.ExpressionTester.Properties.Resources.Run;
            this.evaluateToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.evaluateToolStripMenuItem.Name = "evaluateToolStripMenuItem";
            this.evaluateToolStripMenuItem.ShortcutKeyDisplayString = "F5";
            this.evaluateToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F5;
            this.evaluateToolStripMenuItem.Size = new System.Drawing.Size(197, 22);
            this.evaluateToolStripMenuItem.Text = "Evaluate";
            this.evaluateToolStripMenuItem.Click += new System.EventHandler(this.Run);
            // 
            // toolStripSeparator12
            // 
            this.toolStripSeparator12.Name = "toolStripSeparator12";
            this.toolStripSeparator12.Size = new System.Drawing.Size(194, 6);
            // 
            // addVariableToolStripMenuItem
            // 
            this.addVariableToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("addVariableToolStripMenuItem.Image")));
            this.addVariableToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.White;
            this.addVariableToolStripMenuItem.Name = "addVariableToolStripMenuItem";
            this.addVariableToolStripMenuItem.Size = new System.Drawing.Size(197, 22);
            this.addVariableToolStripMenuItem.Text = "Add Variable";
            this.addVariableToolStripMenuItem.Click += new System.EventHandler(this.AddVariable);
            // 
            // editVariableToolStripMenuItem
            // 
            this.editVariableToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("editVariableToolStripMenuItem.Image")));
            this.editVariableToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.White;
            this.editVariableToolStripMenuItem.Name = "editVariableToolStripMenuItem";
            this.editVariableToolStripMenuItem.Size = new System.Drawing.Size(197, 22);
            this.editVariableToolStripMenuItem.Text = "Edit Variable";
            this.editVariableToolStripMenuItem.Click += new System.EventHandler(this.EditVariable);
            // 
            // deleteVariableToolStripMenuItem
            // 
            this.deleteVariableToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("deleteVariableToolStripMenuItem.Image")));
            this.deleteVariableToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.White;
            this.deleteVariableToolStripMenuItem.Name = "deleteVariableToolStripMenuItem";
            this.deleteVariableToolStripMenuItem.Size = new System.Drawing.Size(197, 22);
            this.deleteVariableToolStripMenuItem.Text = "Delete Variable";
            this.deleteVariableToolStripMenuItem.Click += new System.EventHandler(this.DeleteVariable);
            // 
            // toolStripSeparator13
            // 
            this.toolStripSeparator13.Name = "toolStripSeparator13";
            this.toolStripSeparator13.Size = new System.Drawing.Size(194, 6);
            // 
            // expressionFilePropertiesToolStripMenuItem
            // 
            this.expressionFilePropertiesToolStripMenuItem.Image = global::Konesans.Dts.Tools.ExpressionTester.Properties.Resources.Properties;
            this.expressionFilePropertiesToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.expressionFilePropertiesToolStripMenuItem.Name = "expressionFilePropertiesToolStripMenuItem";
            this.expressionFilePropertiesToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F4;
            this.expressionFilePropertiesToolStripMenuItem.Size = new System.Drawing.Size(197, 22);
            this.expressionFilePropertiesToolStripMenuItem.Text = "Expression Properties";
            this.expressionFilePropertiesToolStripMenuItem.Click += new System.EventHandler(this.ShowExpressionFileProperties);
            // 
            // toolsMenu
            // 
            this.toolsMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.optionsToolStripMenuItem});
            this.toolsMenu.Name = "toolsMenu";
            this.toolsMenu.Size = new System.Drawing.Size(44, 20);
            this.toolsMenu.Text = "&Tools";
            // 
            // optionsToolStripMenuItem
            // 
            this.optionsToolStripMenuItem.Image = global::Konesans.Dts.Tools.ExpressionTester.Properties.Resources.Options;
            this.optionsToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
            this.optionsToolStripMenuItem.Size = new System.Drawing.Size(111, 22);
            this.optionsToolStripMenuItem.Text = "&Options";
            this.optionsToolStripMenuItem.Click += new System.EventHandler(this.ShowOptions);
            // 
            // helpMenu
            // 
            this.helpMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.searchToolStripMenuItem,
            this.toolStripSeparator8,
            this.aboutToolStripMenuItem});
            this.helpMenu.Name = "helpMenu";
            this.helpMenu.Size = new System.Drawing.Size(40, 20);
            this.helpMenu.Text = "&Help";
            // 
            // searchToolStripMenuItem
            // 
            this.searchToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("searchToolStripMenuItem.Image")));
            this.searchToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Black;
            this.searchToolStripMenuItem.Name = "searchToolStripMenuItem";
            this.searchToolStripMenuItem.Size = new System.Drawing.Size(118, 22);
            this.searchToolStripMenuItem.Text = "Online";
            this.searchToolStripMenuItem.Click += new System.EventHandler(this.SearchToolStripMenuItem_Click);
            // 
            // toolStripSeparator8
            // 
            this.toolStripSeparator8.Name = "toolStripSeparator8";
            this.toolStripSeparator8.Size = new System.Drawing.Size(115, 6);
            this.toolStripSeparator8.Visible = false;
            // 
            // aboutToolStripMenuItem
            // 
            this.aboutToolStripMenuItem.Image = global::Konesans.Dts.Tools.ExpressionTester.Properties.Resources.Expression;
            this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            this.aboutToolStripMenuItem.Size = new System.Drawing.Size(118, 22);
            this.aboutToolStripMenuItem.Text = "&About ...";
            this.aboutToolStripMenuItem.Click += new System.EventHandler(this.ShowAboutDialog);
            // 
            // toolStrip
            // 
            this.toolStrip.AllowItemReorder = true;
            this.toolStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.newToolStripButton,
            this.openToolStripButton,
            this.saveToolStripButton,
            this.toolStripSeparatorEndFile,
            this.optionsToolStripButton,
            this.expressionFileSettingsToolStripButton});
            this.toolStrip.LayoutStyle = System.Windows.Forms.ToolStripLayoutStyle.HorizontalStackWithOverflow;
            this.toolStrip.Location = new System.Drawing.Point(0, 24);
            this.toolStrip.Name = "toolStrip";
            this.toolStrip.Size = new System.Drawing.Size(782, 25);
            this.toolStrip.TabIndex = 1;
            this.toolStrip.Text = "ToolStrip";
            // 
            // newToolStripButton
            // 
            this.newToolStripButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.newToolStripButton.Image = global::Konesans.Dts.Tools.ExpressionTester.Properties.Resources.NewDocument;
            this.newToolStripButton.ImageTransparentColor = System.Drawing.Color.Black;
            this.newToolStripButton.Name = "newToolStripButton";
            this.newToolStripButton.Size = new System.Drawing.Size(23, 22);
            this.newToolStripButton.Text = "New";
            this.newToolStripButton.Click += new System.EventHandler(this.New);
            // 
            // openToolStripButton
            // 
            this.openToolStripButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.openToolStripButton.Image = global::Konesans.Dts.Tools.ExpressionTester.Properties.Resources.Open;
            this.openToolStripButton.ImageTransparentColor = System.Drawing.Color.Black;
            this.openToolStripButton.Name = "openToolStripButton";
            this.openToolStripButton.Size = new System.Drawing.Size(23, 22);
            this.openToolStripButton.Text = "Open";
            this.openToolStripButton.Click += new System.EventHandler(this.OpenFile);
            // 
            // saveToolStripButton
            // 
            this.saveToolStripButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.saveToolStripButton.Image = ((System.Drawing.Image)(resources.GetObject("saveToolStripButton.Image")));
            this.saveToolStripButton.ImageTransparentColor = System.Drawing.Color.Black;
            this.saveToolStripButton.Name = "saveToolStripButton";
            this.saveToolStripButton.Size = new System.Drawing.Size(23, 22);
            this.saveToolStripButton.Text = "Save";
            this.saveToolStripButton.Click += new System.EventHandler(this.SaveFile);
            // 
            // toolStripSeparatorEndFile
            // 
            this.toolStripSeparatorEndFile.Name = "toolStripSeparatorEndFile";
            this.toolStripSeparatorEndFile.Size = new System.Drawing.Size(6, 25);
            // 
            // optionsToolStripButton
            // 
            this.optionsToolStripButton.Image = ((System.Drawing.Image)(resources.GetObject("optionsToolStripButton.Image")));
            this.optionsToolStripButton.ImageTransparentColor = System.Drawing.Color.Black;
            this.optionsToolStripButton.Name = "optionsToolStripButton";
            this.optionsToolStripButton.Size = new System.Drawing.Size(64, 22);
            this.optionsToolStripButton.Text = "Options";
            this.optionsToolStripButton.ToolTipText = "Options";
            this.optionsToolStripButton.Click += new System.EventHandler(this.ShowOptions);
            // 
            // expressionFileSettingsToolStripButton
            // 
            this.expressionFileSettingsToolStripButton.Image = global::Konesans.Dts.Tools.ExpressionTester.Properties.Resources.Properties;
            this.expressionFileSettingsToolStripButton.ImageTransparentColor = System.Drawing.Color.Black;
            this.expressionFileSettingsToolStripButton.Name = "expressionFileSettingsToolStripButton";
            this.expressionFileSettingsToolStripButton.Size = new System.Drawing.Size(76, 22);
            this.expressionFileSettingsToolStripButton.Text = "Properties";
            this.expressionFileSettingsToolStripButton.ToolTipText = "Expression Properties";
            this.expressionFileSettingsToolStripButton.Click += new System.EventHandler(this.ShowExpressionFileProperties);
            // 
            // statusStrip
            // 
            this.statusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabelFilename,
            this.toolStripStatusLabelResultType,
            this.toolStripStatusLabelLine,
            this.toolStripStatusLabelColumn});
            this.statusStrip.Location = new System.Drawing.Point(0, 529);
            this.statusStrip.Name = "statusStrip";
            this.statusStrip.Size = new System.Drawing.Size(782, 22);
            this.statusStrip.TabIndex = 2;
            // 
            // toolStripStatusLabelFilename
            // 
            this.toolStripStatusLabelFilename.Name = "toolStripStatusLabelFilename";
            this.toolStripStatusLabelFilename.Size = new System.Drawing.Size(596, 17);
            this.toolStripStatusLabelFilename.Spring = true;
            this.toolStripStatusLabelFilename.Text = "Filename";
            this.toolStripStatusLabelFilename.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // toolStripStatusLabelResultType
            // 
            this.toolStripStatusLabelResultType.Name = "toolStripStatusLabelResultType";
            this.toolStripStatusLabelResultType.Padding = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.toolStripStatusLabelResultType.Size = new System.Drawing.Size(71, 17);
            this.toolStripStatusLabelResultType.Text = "ResultType";
            // 
            // toolStripStatusLabelLine
            // 
            this.toolStripStatusLabelLine.AutoSize = false;
            this.toolStripStatusLabelLine.Name = "toolStripStatusLabelLine";
            this.toolStripStatusLabelLine.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.toolStripStatusLabelLine.Size = new System.Drawing.Size(50, 17);
            this.toolStripStatusLabelLine.Text = "Ln 1";
            this.toolStripStatusLabelLine.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // toolStripStatusLabelColumn
            // 
            this.toolStripStatusLabelColumn.AutoSize = false;
            this.toolStripStatusLabelColumn.Name = "toolStripStatusLabelColumn";
            this.toolStripStatusLabelColumn.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.toolStripStatusLabelColumn.Size = new System.Drawing.Size(50, 17);
            this.toolStripStatusLabelColumn.Text = "Col 1";
            this.toolStripStatusLabelColumn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // expressionEditor
            // 
            this.expressionEditor.ApplicationTitle = "Expression Editor";
            this.expressionEditor.Dock = System.Windows.Forms.DockStyle.Fill;
            this.expressionEditor.EditMode = false;
            this.expressionEditor.Expression = "";
            this.expressionEditor.ExpressionColor = System.Drawing.SystemColors.WindowText;
            this.expressionEditor.ExpressionFont = new System.Drawing.Font("Tahoma", 8F);
            this.expressionEditor.FindOrReplaceMatchCase = false;
            this.expressionEditor.FindOrReplaceSearchUp = false;
            this.expressionEditor.Location = new System.Drawing.Point(0, 49);
            this.expressionEditor.MinimumSize = new System.Drawing.Size(338, 121);
            this.expressionEditor.Name = "expressionEditor";
            this.expressionEditor.ResultColor = System.Drawing.SystemColors.WindowText;
            this.expressionEditor.ResultFont = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.expressionEditor.ResultType = System.TypeCode.Empty;
            this.expressionEditor.ResultTypeValidate = true;
            this.expressionEditor.Saved = false;
            this.expressionEditor.Size = new System.Drawing.Size(782, 480);
            this.expressionEditor.SplitterDistanceExpressions = 233;
            this.expressionEditor.SplitterDistanceMain = 404;
            this.expressionEditor.SplitterDistanceResult = 271;
            this.expressionEditor.TabIndex = 3;
            this.expressionEditor.WordWrap = true;
            this.expressionEditor.FindNotFound += new System.EventHandler<Konesans.Dts.ExpressionEditor.Controls.FindOrReplaceEventArgs>(this.ExpressionEditor_FindNotFound);
            this.expressionEditor.UndoOrRedoCountChanged += new System.EventHandler<Konesans.Dts.ExpressionEditor.Controls.UndoOrRedoCountChangedEventArgs>(this.ExpressionEditor_UndoOrRedoCountChanged);
            this.expressionEditor.CursorPositionChanged += new System.EventHandler<Konesans.Dts.ExpressionEditor.Controls.CursorPositionChangedEventArgs>(this.ExpressionEditor_CursorPositionChanged);
            this.expressionEditor.ResultTypeChanged += new System.EventHandler<Konesans.Dts.ExpressionEditor.Controls.ResultTypeChangedEventArgs>(this.ExpressionEditor_ResultTypeChanged);
            this.expressionEditor.TitleChanged += new System.EventHandler<Konesans.Dts.ExpressionEditor.Controls.TitleChangedEventArgs>(this.ExpressionEditor_TitleChanged);
            this.expressionEditor.VariableSelectionChanged += new System.EventHandler<Konesans.Dts.ExpressionEditor.Controls.VariableSelectionChangedEventArgs>(this.ExpressionEditor_VariableSelectionChanged);
            this.expressionEditor.EditModeChanged += new System.EventHandler<System.EventArgs>(this.ExpressionEditor_EditModeChanged);
            this.expressionEditor.ReplaceAllComplete += new System.EventHandler<Konesans.Dts.ExpressionEditor.Controls.FindOrReplaceEventArgs>(this.ExpressionEditor_ReplaceAllComplete);
            // 
            // Main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(782, 551);
            this.Controls.Add(this.expressionEditor);
            this.Controls.Add(this.statusStrip);
            this.Controls.Add(this.toolStrip);
            this.Controls.Add(this.menuStrip);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.MainMenuStrip = this.menuStrip;
            this.Name = "Main";
            this.Text = "Expression Tester";
            this.Load += new System.EventHandler(this.ExpressionTester_Load);
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.ExpressionTester_FormClosing);
            this.menuStrip.ResumeLayout(false);
            this.menuStrip.PerformLayout();
            this.toolStrip.ResumeLayout(false);
            this.toolStrip.PerformLayout();
            this.statusStrip.ResumeLayout(false);
            this.statusStrip.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion


        private MenuStrip menuStrip;
        private ToolStrip toolStrip;
        private StatusStrip statusStrip;
        private ToolStripSeparator toolStripSeparator4;
        private ToolStripSeparator toolStripSeparator5;
        private ToolStripSeparator toolStripSeparator6;
        private ToolStripSeparator toolStripSeparator7;
        private ToolStripSeparator toolStripSeparator8;
        private ToolStripStatusLabel toolStripStatusLabelFilename;
        private ToolStripMenuItem aboutToolStripMenuItem;
        private ToolStripMenuItem fileMenu;
        private ToolStripMenuItem newToolStripMenuItem;
        private ToolStripMenuItem openToolStripMenuItem;
        private ToolStripMenuItem saveToolStripMenuItem;
        private ToolStripMenuItem saveAsToolStripMenuItem;
        private ToolStripMenuItem exitToolStripMenuItem;
        private ToolStripMenuItem editMenu;
        private ToolStripMenuItem undoToolStripMenuItem;
        private ToolStripMenuItem redoToolStripMenuItem;
        private ToolStripMenuItem cutToolStripMenuItem;
        private ToolStripMenuItem copyToolStripMenuItem;
        private ToolStripMenuItem pasteToolStripMenuItem;
        private ToolStripMenuItem selectAllToolStripMenuItem;
        private ToolStripMenuItem viewMenu;
        private ToolStripMenuItem toolBarToolStripMenuItem;
        private ToolStripMenuItem statusBarToolStripMenuItem;
        private ToolStripMenuItem toolsMenu;
        private ToolStripMenuItem optionsToolStripMenuItem;
        private ToolStripMenuItem helpMenu;
        private ToolStripMenuItem searchToolStripMenuItem;
        private ToolStripButton newToolStripButton;
        private ToolStripButton openToolStripButton;
        private ToolStripButton saveToolStripButton;
        //private ToolTip ToolTip;
        private ToolStripSeparator toolStripSeparator9;
        private ToolStripMenuItem expressionsMenu;
        private ToolStripMenuItem evaluateToolStripMenuItem;
        private ToolStripSeparator toolStripSeparator12;
        private ToolStripMenuItem recentFilesToolStripMenuItem;
        private ToolStripMenuItem recentExpressionFilesPlaceHolderStripMenuItem;
        private ToolStripMenuItem addVariableToolStripMenuItem;
        private ToolStripMenuItem deleteVariableToolStripMenuItem;
        private ToolStripMenuItem editVariableToolStripMenuItem;
        private ToolStripButton expressionFileSettingsToolStripButton;
        private ToolStripMenuItem expressionFilePropertiesToolStripMenuItem;
        private ToolStripSeparator toolStripSeparator13;
        private ExpressionEditorView expressionEditor;
        private ToolStripStatusLabel toolStripStatusLabelResultType;
        private ToolStripSeparator toolStripSeparator3;
        private ToolStripMenuItem findToolStripMenuItem;
        private ToolStripMenuItem replaceToolStripMenuItem;
        private ToolStripStatusLabel toolStripStatusLabelLine;
        private ToolStripStatusLabel toolStripStatusLabelColumn;
        private ToolStripMenuItem wordWrapToolStripMenuItem;
        private ToolStripSeparator toolStripSeparator16;
        private ToolStripMenuItem saveAsTemplateToolStripMenuItem;
        private ToolStripMenuItem editFunctionsToolStripMenuItem;
        private ToolStripSeparator toolStripSeparatorEndFile;
        private ToolStripButton optionsToolStripButton;
    }
}



