// <auto-generated/>

namespace Konesans.Dts.ExpressionEditor.Controls
{
    partial class ExpressionFunctionsEditor
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.textBoxSyntax = new System.Windows.Forms.TextBox();
            this.textBoxSyntaxLabel = new System.Windows.Forms.TextBox();
            this.textBoxDescription = new System.Windows.Forms.TextBox();
            this.groupBoxBorder = new System.Windows.Forms.GroupBox();
            this.label5 = new System.Windows.Forms.Label();
            this.labelSyntax = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.labelText = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.toolStripButtonNewExpressionGroup = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonNewExpressionFunction = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonExpressionDelete = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripButtonUp = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonDown = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonLeft = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonRight = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripButtonSaveFunctions = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonCloseFunctionEditor = new System.Windows.Forms.ToolStripButton();
            this.groupBoxBorder.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // textBoxSyntax
            // 
            this.textBoxSyntax.AcceptsReturn = true;
            this.textBoxSyntax.AcceptsTab = true;
            this.textBoxSyntax.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.textBoxSyntax.Location = new System.Drawing.Point(82, 133);
            this.textBoxSyntax.Multiline = true;
            this.textBoxSyntax.Name = "textBoxSyntax";
            this.textBoxSyntax.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.textBoxSyntax.Size = new System.Drawing.Size(422, 183);
            this.textBoxSyntax.TabIndex = 0;
            this.textBoxSyntax.Leave += new System.EventHandler(this.TextBoxSyntax_Leave);
            // 
            // textBoxSyntaxLabel
            // 
            this.textBoxSyntaxLabel.Location = new System.Drawing.Point(82, 29);
            this.textBoxSyntaxLabel.Name = "textBoxSyntaxLabel";
            this.textBoxSyntaxLabel.Size = new System.Drawing.Size(416, 20);
            this.textBoxSyntaxLabel.TabIndex = 1;
            this.textBoxSyntaxLabel.Leave += new System.EventHandler(this.TextBoxSyntaxLabel_Leave);
            // 
            // textBoxDescription
            // 
            this.textBoxDescription.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.textBoxDescription.Location = new System.Drawing.Point(82, 81);
            this.textBoxDescription.Name = "textBoxDescription";
            this.textBoxDescription.Size = new System.Drawing.Size(422, 20);
            this.textBoxDescription.TabIndex = 2;
            this.textBoxDescription.Leave += new System.EventHandler(this.TextBoxDescription_Leave);
            // 
            // groupBoxBorder
            // 
            this.groupBoxBorder.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBoxBorder.Controls.Add(this.label5);
            this.groupBoxBorder.Controls.Add(this.labelSyntax);
            this.groupBoxBorder.Controls.Add(this.label1);
            this.groupBoxBorder.Controls.Add(this.textBoxSyntaxLabel);
            this.groupBoxBorder.Controls.Add(this.labelText);
            this.groupBoxBorder.Controls.Add(this.textBoxDescription);
            this.groupBoxBorder.Controls.Add(this.textBoxSyntax);
            this.groupBoxBorder.Controls.Add(this.label2);
            this.groupBoxBorder.Controls.Add(this.label3);
            this.groupBoxBorder.Location = new System.Drawing.Point(0, 30);
            this.groupBoxBorder.Name = "groupBoxBorder";
            this.groupBoxBorder.Size = new System.Drawing.Size(510, 380);
            this.groupBoxBorder.TabIndex = 3;
            this.groupBoxBorder.TabStop = false;
            this.groupBoxBorder.Text = "Functions && Snippets Editor";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(92, 104);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(319, 13);
            this.label5.TabIndex = 12;
            this.label5.Text = "Description of the usage and behaviour of the function or snippert.";
            // 
            // labelSyntax
            // 
            this.labelSyntax.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.labelSyntax.AutoEllipsis = true;
            this.labelSyntax.Location = new System.Drawing.Point(92, 319);
            this.labelSyntax.Name = "labelSyntax";
            this.labelSyntax.Size = new System.Drawing.Size(412, 44);
            this.labelSyntax.TabIndex = 11;
            this.labelSyntax.Text = "Optional.  For simple functions or snippets use Label only. For complex functions" +
                " enter the display text in Label and the full expression text in Syntax.";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(92, 52);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(242, 13);
            this.label1.TabIndex = 10;
            this.label1.Text = "The display text shown in the functions tree  view.";
            // 
            // labelText
            // 
            this.labelText.AutoSize = true;
            this.labelText.Location = new System.Drawing.Point(11, 136);
            this.labelText.Name = "labelText";
            this.labelText.Size = new System.Drawing.Size(42, 13);
            this.labelText.TabIndex = 3;
            this.labelText.Text = "Syntax:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(11, 32);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(36, 13);
            this.label2.TabIndex = 4;
            this.label2.Text = "Label:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(11, 84);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(63, 13);
            this.label3.TabIndex = 5;
            this.label3.Text = "Description:";
            // 
            // toolStrip1
            // 
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripButtonNewExpressionGroup,
            this.toolStripButtonNewExpressionFunction,
            this.toolStripButtonExpressionDelete,
            this.toolStripSeparator1,
            this.toolStripButtonUp,
            this.toolStripButtonDown,
            this.toolStripButtonLeft,
            this.toolStripButtonRight,
            this.toolStripSeparator2,
            this.toolStripButtonSaveFunctions,
            this.toolStripButtonCloseFunctionEditor});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(510, 25);
            this.toolStrip1.TabIndex = 4;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // toolStripButtonNewExpressionGroup
            // 
            this.toolStripButtonNewExpressionGroup.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonNewExpressionGroup.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.NewFolder;
            this.toolStripButtonNewExpressionGroup.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonNewExpressionGroup.Name = "toolStripButtonNewExpressionGroup";
            this.toolStripButtonNewExpressionGroup.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonNewExpressionGroup.Text = "New group";
            this.toolStripButtonNewExpressionGroup.Click += new System.EventHandler(this.ToolStripButtonNewExpressionGroup_Click);
            // 
            // toolStripButtonNewExpressionFunction
            // 
            this.toolStripButtonNewExpressionFunction.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonNewExpressionFunction.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.ExpressionlNew;
            this.toolStripButtonNewExpressionFunction.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonNewExpressionFunction.Name = "toolStripButtonNewExpressionFunction";
            this.toolStripButtonNewExpressionFunction.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonNewExpressionFunction.Text = "New function";
            this.toolStripButtonNewExpressionFunction.Click += new System.EventHandler(this.ToolStripButtonNewExpressionFunction_Click);
            // 
            // toolStripButtonExpressionDelete
            // 
            this.toolStripButtonExpressionDelete.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonExpressionDelete.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.Delete;
            this.toolStripButtonExpressionDelete.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonExpressionDelete.Name = "toolStripButtonExpressionDelete";
            this.toolStripButtonExpressionDelete.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonExpressionDelete.Text = "Delete group or function";
            this.toolStripButtonExpressionDelete.Click += new System.EventHandler(this.ToolStripButtonExpressionDelete_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(6, 25);
            // 
            // toolStripButtonUp
            // 
            this.toolStripButtonUp.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonUp.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.BlueUp16;
            this.toolStripButtonUp.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonUp.Name = "toolStripButtonUp";
            this.toolStripButtonUp.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonUp.Text = "Move up";
            this.toolStripButtonUp.Click += new System.EventHandler(this.ToolStripButtonUp_Click);
            // 
            // toolStripButtonDown
            // 
            this.toolStripButtonDown.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonDown.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.BlueDown16;
            this.toolStripButtonDown.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonDown.Name = "toolStripButtonDown";
            this.toolStripButtonDown.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonDown.Text = "Move down";
            this.toolStripButtonDown.Click += new System.EventHandler(this.ToolStripButtonDown_Click);
            // 
            // toolStripButtonLeft
            // 
            this.toolStripButtonLeft.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonLeft.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.BlueLeft16;
            this.toolStripButtonLeft.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonLeft.Name = "toolStripButtonLeft";
            this.toolStripButtonLeft.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonLeft.Text = "Move left";
            this.toolStripButtonLeft.Click += new System.EventHandler(this.ToolStripButtonLeft_Click);
            // 
            // toolStripButtonRight
            // 
            this.toolStripButtonRight.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonRight.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.BlueRight16;
            this.toolStripButtonRight.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonRight.Name = "toolStripButtonRight";
            this.toolStripButtonRight.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonRight.Text = "Move right";
            this.toolStripButtonRight.Click += new System.EventHandler(this.ToolStripButtonRight_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(6, 25);
            // 
            // toolStripButtonSaveFunctions
            // 
            this.toolStripButtonSaveFunctions.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonSaveFunctions.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.Save;
            this.toolStripButtonSaveFunctions.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonSaveFunctions.Name = "toolStripButtonSaveFunctions";
            this.toolStripButtonSaveFunctions.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonSaveFunctions.Text = "Save functions";
            this.toolStripButtonSaveFunctions.Click += new System.EventHandler(this.ToolStripButtonSaveFunctions_Click);
            // 
            // toolStripButtonCloseFunctionEditor
            // 
            this.toolStripButtonCloseFunctionEditor.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
            this.toolStripButtonCloseFunctionEditor.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.ExpressionEdit;
            this.toolStripButtonCloseFunctionEditor.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonCloseFunctionEditor.Name = "toolStripButtonCloseFunctionEditor";
            this.toolStripButtonCloseFunctionEditor.Size = new System.Drawing.Size(53, 22);
            this.toolStripButtonCloseFunctionEditor.Text = "Close";
            this.toolStripButtonCloseFunctionEditor.ToolTipText = "Close functions & snippets editor";
            this.toolStripButtonCloseFunctionEditor.Click += new System.EventHandler(this.toolStripButtonCloseFunctionEditor_Click);
            // 
            // ExpressionFunctionsEditor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.groupBoxBorder);
            this.Controls.Add(this.toolStrip1);
            this.Name = "ExpressionFunctionsEditor";
            this.Size = new System.Drawing.Size(510, 410);
            this.groupBoxBorder.ResumeLayout(false);
            this.groupBoxBorder.PerformLayout();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TextBox textBoxSyntax;
        private System.Windows.Forms.TextBox textBoxSyntaxLabel;
        private System.Windows.Forms.TextBox textBoxDescription;
        private System.Windows.Forms.GroupBox groupBoxBorder;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label labelText;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label labelSyntax;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton toolStripButtonUp;
        private System.Windows.Forms.ToolStripButton toolStripButtonDown;
        private System.Windows.Forms.ToolStripButton toolStripButtonRight;
        private System.Windows.Forms.ToolStripButton toolStripButtonLeft;
        private System.Windows.Forms.ToolStripButton toolStripButtonNewExpressionGroup;
        private System.Windows.Forms.ToolStripButton toolStripButtonNewExpressionFunction;
        private System.Windows.Forms.ToolStripButton toolStripButtonExpressionDelete;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripButton toolStripButtonSaveFunctions;
        private System.Windows.Forms.ToolStripButton toolStripButtonCloseFunctionEditor;
    }
}
