// <auto-generated/>

namespace Konesans.Dts.ExpressionEditor.Controls
{
    using Konesans.Dts.ExpressionEditor.Controls;

    /// <summary>
    /// Expression editor control
    /// </summary>
    partial class ExpressionEditorView
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Releases unmanaged and - optionally - managed resources
        /// </summary>
        /// <param name="disposing"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
                if (this.host != null) this.host.Dispose();

            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.imageListIcons = new System.Windows.Forms.ImageList(this.components);
            this.contextMenuStripVariablesFunctions = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.addVariableToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editVariableToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.deleteVariableToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparatorEditFunctions = new System.Windows.Forms.ToolStripSeparator();
            this.editFunctionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolTip = new System.Windows.Forms.ToolTip(this.components);
            this.splitContainerMain = new System.Windows.Forms.SplitContainer();
            this.splitContainerFunctionExpressions = new System.Windows.Forms.SplitContainer();
            this.treeViewVariablesFunctions = new System.Windows.Forms.TreeView();
            this.richPanelFunctionsCaption = new Konesans.Dts.ExpressionEditor.Controls.RichPanel();
            this.splitContainerExpressionResult = new System.Windows.Forms.SplitContainer();
            this.richTxtExpressionBorderPanel = new Konesans.Dts.ExpressionEditor.Controls.RichPanel();
            this.ExpressionTextBox = new System.Windows.Forms.RichTextBox();
            this.contextMenuStripTextPanes = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.undoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.redoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparatorUndo = new System.Windows.Forms.ToolStripSeparator();
            this.cutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.copyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.pasteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparatorTextEdit = new System.Windows.Forms.ToolStripSeparator();
            this.selectAllToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.borderedPanelExpressionCaption = new Konesans.Dts.ExpressionEditor.Controls.RichPanel();
            this.richTextResultBorderPanel = new Konesans.Dts.ExpressionEditor.Controls.RichPanel();
            this.richTextResult = new System.Windows.Forms.RichTextBox();
            this.evaluatorResultPableCaption = new Konesans.Dts.ExpressionEditor.Controls.RichPanel();
            this.linkEvaluate = new System.Windows.Forms.LinkLabel();
            this.expressionEditorViewEditorPanel = new Konesans.Dts.ExpressionEditor.Controls.ExpressionFunctionsEditor();
            this.descriptionPanel = new Konesans.Dts.ExpressionEditor.Controls.RichPanel();
            this.labelHelpText = new System.Windows.Forms.Label();
            this.panelTopMargin = new System.Windows.Forms.Panel();
            this.contextMenuStripVariablesFunctions.SuspendLayout();
            this.splitContainerMain.Panel1.SuspendLayout();
            this.splitContainerMain.Panel2.SuspendLayout();
            this.splitContainerMain.SuspendLayout();
            this.splitContainerFunctionExpressions.Panel1.SuspendLayout();
            this.splitContainerFunctionExpressions.Panel2.SuspendLayout();
            this.splitContainerFunctionExpressions.SuspendLayout();
            this.splitContainerExpressionResult.Panel1.SuspendLayout();
            this.splitContainerExpressionResult.Panel2.SuspendLayout();
            this.splitContainerExpressionResult.SuspendLayout();
            this.richTxtExpressionBorderPanel.SuspendLayout();
            this.contextMenuStripTextPanes.SuspendLayout();
            this.richTextResultBorderPanel.SuspendLayout();
            this.evaluatorResultPableCaption.SuspendLayout();
            this.descriptionPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // imageListIcons
            // 
            this.imageListIcons.ColorDepth = System.Windows.Forms.ColorDepth.Depth32Bit;
            this.imageListIcons.ImageSize = new System.Drawing.Size(16, 16);
            this.imageListIcons.TransparentColor = System.Drawing.Color.Transparent;
            // 
            // contextMenuStripVariablesFunctions
            // 
            this.contextMenuStripVariablesFunctions.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.addVariableToolStripMenuItem,
            this.editVariableToolStripMenuItem,
            this.deleteVariableToolStripMenuItem,
            this.toolStripSeparatorEditFunctions,
            this.editFunctionsToolStripMenuItem});
            this.contextMenuStripVariablesFunctions.Name = "contextMenuStripVariables";
            this.contextMenuStripVariablesFunctions.Size = new System.Drawing.Size(147, 98);
            this.contextMenuStripVariablesFunctions.ItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.ContextMenuStripVariablesFunctions_ItemClicked);
            this.contextMenuStripVariablesFunctions.Opening += new System.ComponentModel.CancelEventHandler(this.ContextMenuStripVariablesFunctions_Opening);
            // 
            // addVariableToolStripMenuItem
            // 
            this.addVariableToolStripMenuItem.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.VariableNew;
            this.addVariableToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.White;
            this.addVariableToolStripMenuItem.Name = "addVariableToolStripMenuItem";
            this.addVariableToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.addVariableToolStripMenuItem.Text = "Add Variable";
            // 
            // editVariableToolStripMenuItem
            // 
            this.editVariableToolStripMenuItem.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.VariableEdit;
            this.editVariableToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.White;
            this.editVariableToolStripMenuItem.Name = "editVariableToolStripMenuItem";
            this.editVariableToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.editVariableToolStripMenuItem.Text = "Edit Variable";
            // 
            // deleteVariableToolStripMenuItem
            // 
            this.deleteVariableToolStripMenuItem.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.VariableDelete;
            this.deleteVariableToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.White;
            this.deleteVariableToolStripMenuItem.Name = "deleteVariableToolStripMenuItem";
            this.deleteVariableToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.deleteVariableToolStripMenuItem.Text = "Delete Variable";
            // 
            // toolStripSeparatorEditFunctions
            // 
            this.toolStripSeparatorEditFunctions.Name = "toolStripSeparatorEditFunctions";
            this.toolStripSeparatorEditFunctions.Size = new System.Drawing.Size(143, 6);
            // 
            // editFunctionsToolStripMenuItem
            // 
            this.editFunctionsToolStripMenuItem.CheckOnClick = true;
            this.editFunctionsToolStripMenuItem.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.ExpressionEdit;
            this.editFunctionsToolStripMenuItem.Name = "editFunctionsToolStripMenuItem";
            this.editFunctionsToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.editFunctionsToolStripMenuItem.Text = "Edit Functions";
            // 
            // toolTip
            // 
            this.toolTip.IsBalloon = true;
            // 
            // splitContainerMain
            // 
            this.splitContainerMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainerMain.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
            this.splitContainerMain.Location = new System.Drawing.Point(0, 4);
            this.splitContainerMain.Margin = new System.Windows.Forms.Padding(3, 20, 3, 3);
            this.splitContainerMain.Name = "splitContainerMain";
            this.splitContainerMain.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainerMain.Panel1
            // 
            this.splitContainerMain.Panel1.Controls.Add(this.splitContainerFunctionExpressions);
            // 
            // splitContainerMain.Panel2
            // 
            this.splitContainerMain.Panel2.Controls.Add(this.descriptionPanel);
            this.splitContainerMain.Size = new System.Drawing.Size(747, 457);
            this.splitContainerMain.SplitterDistance = 409;
            this.splitContainerMain.TabIndex = 12;
            // 
            // splitContainerFunctionExpressions
            // 
            this.splitContainerFunctionExpressions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainerFunctionExpressions.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.splitContainerFunctionExpressions.Location = new System.Drawing.Point(0, 0);
            this.splitContainerFunctionExpressions.Name = "splitContainerFunctionExpressions";
            // 
            // splitContainerFunctionExpressions.Panel1
            // 
            this.splitContainerFunctionExpressions.Panel1.Controls.Add(this.treeViewVariablesFunctions);
            this.splitContainerFunctionExpressions.Panel1.Controls.Add(this.richPanelFunctionsCaption);
            // 
            // splitContainerFunctionExpressions.Panel2
            // 
            this.splitContainerFunctionExpressions.Panel2.Controls.Add(this.splitContainerExpressionResult);
            this.splitContainerFunctionExpressions.Panel2.Controls.Add(this.expressionEditorViewEditorPanel);
            this.splitContainerFunctionExpressions.Size = new System.Drawing.Size(747, 409);
            this.splitContainerFunctionExpressions.SplitterDistance = 233;
            this.splitContainerFunctionExpressions.TabIndex = 0;
            // 
            // treeViewVariablesFunctions
            // 
            this.treeViewVariablesFunctions.ContextMenuStrip = this.contextMenuStripVariablesFunctions;
            this.treeViewVariablesFunctions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treeViewVariablesFunctions.HideSelection = false;
            this.treeViewVariablesFunctions.Location = new System.Drawing.Point(0, 21);
            this.treeViewVariablesFunctions.Name = "treeViewVariablesFunctions";
            this.treeViewVariablesFunctions.Size = new System.Drawing.Size(233, 388);
            this.treeViewVariablesFunctions.TabIndex = 3;
            this.treeViewVariablesFunctions.NodeMouseDoubleClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.TreeViewVariablesFunctions_NodeMouseDoubleClick);
            this.treeViewVariablesFunctions.AfterCollapse += new System.Windows.Forms.TreeViewEventHandler(this.TreeViewVariablesFunctions_AfterCollapse);
            this.treeViewVariablesFunctions.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.TreeViewVariablesFunctions_AfterSelect);
            this.treeViewVariablesFunctions.NodeMouseClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.TreeViewVariablesFunctions_NodeMouseClick);
            this.treeViewVariablesFunctions.AfterExpand += new System.Windows.Forms.TreeViewEventHandler(this.TreeViewVariablesFunctions_AfterExpand);
            this.treeViewVariablesFunctions.ItemDrag += new System.Windows.Forms.ItemDragEventHandler(this.TreeViewVariablesFunctions_ItemDrag);
            // 
            // richPanelFunctionsCaption
            // 
            this.richPanelFunctionsCaption.BorderColor = System.Drawing.SystemColors.ControlDark;
            this.richPanelFunctionsCaption.BorderWidth = 1;
            this.richPanelFunctionsCaption.Caption = true;
            this.richPanelFunctionsCaption.CaptionBeginColor = System.Drawing.SystemColors.GradientActiveCaption;
            this.richPanelFunctionsCaption.CaptionEndColor = System.Drawing.SystemColors.ActiveCaption;
            this.richPanelFunctionsCaption.CaptionGradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.richPanelFunctionsCaption.CaptionHeight = 20;
            this.richPanelFunctionsCaption.CaptionText = " Variables & Functions";
            this.richPanelFunctionsCaption.CaptionTextAlignment = System.Drawing.StringAlignment.Near;
            this.richPanelFunctionsCaption.CaptionTextColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.richPanelFunctionsCaption.Dock = System.Windows.Forms.DockStyle.Top;
            this.richPanelFunctionsCaption.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold);
            this.richPanelFunctionsCaption.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.richPanelFunctionsCaption.GradientEnd = System.Drawing.SystemColors.InactiveCaption;
            this.richPanelFunctionsCaption.GradientStart = System.Drawing.SystemColors.GradientInactiveCaption;
            this.richPanelFunctionsCaption.Location = new System.Drawing.Point(0, 0);
            this.richPanelFunctionsCaption.Name = "richPanelFunctionsCaption";
            this.richPanelFunctionsCaption.PanelIcon = null;
            this.richPanelFunctionsCaption.ShowBorder = true;
            this.richPanelFunctionsCaption.ShowIcon = false;
            this.richPanelFunctionsCaption.Size = new System.Drawing.Size(233, 21);
            this.richPanelFunctionsCaption.TabIndex = 0;
            this.richPanelFunctionsCaption.TextAntiAlias = true;
            // 
            // splitContainerExpressionResult
            // 
            this.splitContainerExpressionResult.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainerExpressionResult.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
            this.splitContainerExpressionResult.Location = new System.Drawing.Point(0, 0);
            this.splitContainerExpressionResult.Name = "splitContainerExpressionResult";
            this.splitContainerExpressionResult.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainerExpressionResult.Panel1
            // 
            this.splitContainerExpressionResult.Panel1.Controls.Add(this.richTxtExpressionBorderPanel);
            this.splitContainerExpressionResult.Panel1.Controls.Add(this.borderedPanelExpressionCaption);
            // 
            // splitContainerExpressionResult.Panel2
            // 
            this.splitContainerExpressionResult.Panel2.Controls.Add(this.richTextResultBorderPanel);
            this.splitContainerExpressionResult.Panel2.Controls.Add(this.evaluatorResultPableCaption);
            this.splitContainerExpressionResult.Size = new System.Drawing.Size(510, 409);
            this.splitContainerExpressionResult.SplitterDistance = 276;
            this.splitContainerExpressionResult.TabIndex = 0;
            // 
            // richTxtExpressionBorderPanel
            // 
            this.richTxtExpressionBorderPanel.BackColor = System.Drawing.Color.Transparent;
            this.richTxtExpressionBorderPanel.BorderColor = System.Drawing.SystemColors.ControlDark;
            this.richTxtExpressionBorderPanel.BorderWidth = 1;
            this.richTxtExpressionBorderPanel.Caption = false;
            this.richTxtExpressionBorderPanel.CaptionBeginColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(225)))), ((int)(((byte)(155)))));
            this.richTxtExpressionBorderPanel.CaptionEndColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(78)))));
            this.richTxtExpressionBorderPanel.CaptionGradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.richTxtExpressionBorderPanel.CaptionHeight = 24;
            this.richTxtExpressionBorderPanel.CaptionText = "Panel";
            this.richTxtExpressionBorderPanel.CaptionTextAlignment = System.Drawing.StringAlignment.Near;
            this.richTxtExpressionBorderPanel.CaptionTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.richTxtExpressionBorderPanel.Controls.Add(this.ExpressionTextBox);
            this.richTxtExpressionBorderPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.richTxtExpressionBorderPanel.Font = new System.Drawing.Font("Tahoma", 8F);
            this.richTxtExpressionBorderPanel.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.richTxtExpressionBorderPanel.GradientEnd = System.Drawing.SystemColors.Window;
            this.richTxtExpressionBorderPanel.GradientStart = System.Drawing.SystemColors.Window;
            this.richTxtExpressionBorderPanel.Location = new System.Drawing.Point(0, 21);
            this.richTxtExpressionBorderPanel.Name = "richTxtExpressionBorderPanel";
            this.richTxtExpressionBorderPanel.Padding = new System.Windows.Forms.Padding(1, 1, 1, 5);
            this.richTxtExpressionBorderPanel.PanelIcon = null;
            this.richTxtExpressionBorderPanel.ShowBorder = true;
            this.richTxtExpressionBorderPanel.ShowIcon = false;
            this.richTxtExpressionBorderPanel.Size = new System.Drawing.Size(510, 255);
            this.richTxtExpressionBorderPanel.TabIndex = 4;
            this.richTxtExpressionBorderPanel.TextAntiAlias = true;
            // 
            // ExpressionTextBox
            // 
            this.ExpressionTextBox.AcceptsTab = true;
            this.ExpressionTextBox.AutoWordSelection = true;
            this.ExpressionTextBox.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.ExpressionTextBox.ContextMenuStrip = this.contextMenuStripTextPanes;
            this.ExpressionTextBox.DetectUrls = false;
            this.ExpressionTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ExpressionTextBox.HideSelection = false;
            this.ExpressionTextBox.Location = new System.Drawing.Point(1, 1);
            this.ExpressionTextBox.Name = "ExpressionTextBox";
            this.ExpressionTextBox.Size = new System.Drawing.Size(508, 249);
            this.ExpressionTextBox.TabIndex = 0;
            this.ExpressionTextBox.Text = "";
            this.ExpressionTextBox.SelectionChanged += new System.EventHandler(this.ExpressionTextBox_SelectionChanged);
            this.ExpressionTextBox.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.RichTxtExpression_MouseDoubleClick);
            this.ExpressionTextBox.Enter += new System.EventHandler(this.TextControls_Enter);
            this.ExpressionTextBox.Leave += new System.EventHandler(this.TextControls_Leave);
            this.ExpressionTextBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ExpressionTextBox_KeyDown);
            this.ExpressionTextBox.TextChanged += new System.EventHandler(this.RichTxtExpression_TextChanged);
            // 
            // contextMenuStripTextPanes
            // 
            this.contextMenuStripTextPanes.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.undoToolStripMenuItem,
            this.redoToolStripMenuItem,
            this.toolStripSeparatorUndo,
            this.cutToolStripMenuItem,
            this.copyToolStripMenuItem,
            this.pasteToolStripMenuItem,
            this.toolStripSeparatorTextEdit,
            this.selectAllToolStripMenuItem});
            this.contextMenuStripTextPanes.Name = "contextMenuStripTextPanes";
            this.contextMenuStripTextPanes.Size = new System.Drawing.Size(157, 148);
            this.contextMenuStripTextPanes.Opening += new System.ComponentModel.CancelEventHandler(this.ContextMenuStripTextPanes_Opening);
            // 
            // undoToolStripMenuItem
            // 
            this.undoToolStripMenuItem.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.EditUndo;
            this.undoToolStripMenuItem.Name = "undoToolStripMenuItem";
            this.undoToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Z)));
            this.undoToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.undoToolStripMenuItem.Text = "&Undo";
            this.undoToolStripMenuItem.Click += new System.EventHandler(this.UndoToolStripMenuItem_Click);
            // 
            // redoToolStripMenuItem
            // 
            this.redoToolStripMenuItem.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.EditRedo;
            this.redoToolStripMenuItem.Name = "redoToolStripMenuItem";
            this.redoToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Y)));
            this.redoToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.redoToolStripMenuItem.Text = "&Redo";
            this.redoToolStripMenuItem.Click += new System.EventHandler(this.RedoToolStripMenuItem_Click);
            // 
            // toolStripSeparatorUndo
            // 
            this.toolStripSeparatorUndo.Name = "toolStripSeparatorUndo";
            this.toolStripSeparatorUndo.Size = new System.Drawing.Size(153, 6);
            // 
            // cutToolStripMenuItem
            // 
            this.cutToolStripMenuItem.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.Cut;
            this.cutToolStripMenuItem.Name = "cutToolStripMenuItem";
            this.cutToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.X)));
            this.cutToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.cutToolStripMenuItem.Text = "Cu&t";
            this.cutToolStripMenuItem.Click += new System.EventHandler(this.CutToolStripMenuItem_Click);
            // 
            // copyToolStripMenuItem
            // 
            this.copyToolStripMenuItem.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.Copy;
            this.copyToolStripMenuItem.Name = "copyToolStripMenuItem";
            this.copyToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.C)));
            this.copyToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.copyToolStripMenuItem.Text = "&Copy";
            this.copyToolStripMenuItem.Click += new System.EventHandler(this.CopyToolStripMenuItem_Click);
            // 
            // pasteToolStripMenuItem
            // 
            this.pasteToolStripMenuItem.Image = global::Konesans.Dts.ExpressionEditor.Properties.Resources.Paste;
            this.pasteToolStripMenuItem.Name = "pasteToolStripMenuItem";
            this.pasteToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.V)));
            this.pasteToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.pasteToolStripMenuItem.Text = "&Paste";
            this.pasteToolStripMenuItem.Click += new System.EventHandler(this.PasteToolStripMenuItem_Click);
            // 
            // toolStripSeparatorTextEdit
            // 
            this.toolStripSeparatorTextEdit.Name = "toolStripSeparatorTextEdit";
            this.toolStripSeparatorTextEdit.Size = new System.Drawing.Size(153, 6);
            // 
            // selectAllToolStripMenuItem
            // 
            this.selectAllToolStripMenuItem.Name = "selectAllToolStripMenuItem";
            this.selectAllToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.A)));
            this.selectAllToolStripMenuItem.Size = new System.Drawing.Size(156, 22);
            this.selectAllToolStripMenuItem.Text = "Select All";
            this.selectAllToolStripMenuItem.Click += new System.EventHandler(this.SelectAllToolStripMenuItem_Click);
            // 
            // borderedPanelExpressionCaption
            // 
            this.borderedPanelExpressionCaption.BackColor = System.Drawing.SystemColors.ControlLight;
            this.borderedPanelExpressionCaption.BorderColor = System.Drawing.SystemColors.ControlDark;
            this.borderedPanelExpressionCaption.BorderWidth = 1;
            this.borderedPanelExpressionCaption.Caption = true;
            this.borderedPanelExpressionCaption.CaptionBeginColor = System.Drawing.SystemColors.GradientActiveCaption;
            this.borderedPanelExpressionCaption.CaptionEndColor = System.Drawing.SystemColors.ActiveCaption;
            this.borderedPanelExpressionCaption.CaptionGradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.borderedPanelExpressionCaption.CaptionHeight = 20;
            this.borderedPanelExpressionCaption.CaptionText = " Expression";
            this.borderedPanelExpressionCaption.CaptionTextAlignment = System.Drawing.StringAlignment.Near;
            this.borderedPanelExpressionCaption.CaptionTextColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.borderedPanelExpressionCaption.Dock = System.Windows.Forms.DockStyle.Top;
            this.borderedPanelExpressionCaption.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.borderedPanelExpressionCaption.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.borderedPanelExpressionCaption.GradientEnd = System.Drawing.SystemColors.InactiveCaption;
            this.borderedPanelExpressionCaption.GradientStart = System.Drawing.SystemColors.GradientInactiveCaption;
            this.borderedPanelExpressionCaption.Location = new System.Drawing.Point(0, 0);
            this.borderedPanelExpressionCaption.Name = "borderedPanelExpressionCaption";
            this.borderedPanelExpressionCaption.PanelIcon = null;
            this.borderedPanelExpressionCaption.ShowBorder = true;
            this.borderedPanelExpressionCaption.ShowIcon = false;
            this.borderedPanelExpressionCaption.Size = new System.Drawing.Size(510, 21);
            this.borderedPanelExpressionCaption.TabIndex = 3;
            this.borderedPanelExpressionCaption.TextAntiAlias = true;
            // 
            // richTextResultBorderPanel
            // 
            this.richTextResultBorderPanel.BackColor = System.Drawing.Color.Transparent;
            this.richTextResultBorderPanel.BorderColor = System.Drawing.SystemColors.ControlDark;
            this.richTextResultBorderPanel.BorderWidth = 1;
            this.richTextResultBorderPanel.Caption = false;
            this.richTextResultBorderPanel.CaptionBeginColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(225)))), ((int)(((byte)(155)))));
            this.richTextResultBorderPanel.CaptionEndColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(78)))));
            this.richTextResultBorderPanel.CaptionGradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.richTextResultBorderPanel.CaptionHeight = 24;
            this.richTextResultBorderPanel.CaptionText = "Panel";
            this.richTextResultBorderPanel.CaptionTextAlignment = System.Drawing.StringAlignment.Near;
            this.richTextResultBorderPanel.CaptionTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.richTextResultBorderPanel.Controls.Add(this.richTextResult);
            this.richTextResultBorderPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.richTextResultBorderPanel.Font = new System.Drawing.Font("Tahoma", 8F);
            this.richTextResultBorderPanel.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.richTextResultBorderPanel.GradientEnd = System.Drawing.SystemColors.Window;
            this.richTextResultBorderPanel.GradientStart = System.Drawing.SystemColors.Window;
            this.richTextResultBorderPanel.Location = new System.Drawing.Point(0, 21);
            this.richTextResultBorderPanel.Name = "richTextResultBorderPanel";
            this.richTextResultBorderPanel.Padding = new System.Windows.Forms.Padding(1, 1, 1, 5);
            this.richTextResultBorderPanel.PanelIcon = null;
            this.richTextResultBorderPanel.ShowBorder = true;
            this.richTextResultBorderPanel.ShowIcon = false;
            this.richTextResultBorderPanel.Size = new System.Drawing.Size(510, 108);
            this.richTextResultBorderPanel.TabIndex = 5;
            this.richTextResultBorderPanel.TextAntiAlias = true;
            // 
            // richTextResult
            // 
            this.richTextResult.BackColor = System.Drawing.SystemColors.Info;
            this.richTextResult.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.richTextResult.ContextMenuStrip = this.contextMenuStripTextPanes;
            this.richTextResult.Dock = System.Windows.Forms.DockStyle.Fill;
            this.richTextResult.Location = new System.Drawing.Point(1, 1);
            this.richTextResult.Name = "richTextResult";
            this.richTextResult.ReadOnly = true;
            this.richTextResult.Size = new System.Drawing.Size(508, 102);
            this.richTextResult.TabIndex = 2;
            this.richTextResult.Text = "";
            this.richTextResult.SelectionChanged += new System.EventHandler(this.ExpressionTextBox_SelectionChanged);
            this.richTextResult.Enter += new System.EventHandler(this.TextControls_Enter);
            this.richTextResult.Leave += new System.EventHandler(this.TextControls_Leave);
            // 
            // evaluatorResultPableCaption
            // 
            this.evaluatorResultPableCaption.BackColor = System.Drawing.SystemColors.ControlLight;
            this.evaluatorResultPableCaption.BorderColor = System.Drawing.SystemColors.ControlDark;
            this.evaluatorResultPableCaption.BorderWidth = 1;
            this.evaluatorResultPableCaption.Caption = true;
            this.evaluatorResultPableCaption.CaptionBeginColor = System.Drawing.SystemColors.GradientActiveCaption;
            this.evaluatorResultPableCaption.CaptionEndColor = System.Drawing.SystemColors.ActiveCaption;
            this.evaluatorResultPableCaption.CaptionGradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.evaluatorResultPableCaption.CaptionHeight = 20;
            this.evaluatorResultPableCaption.CaptionText = " Result";
            this.evaluatorResultPableCaption.CaptionTextAlignment = System.Drawing.StringAlignment.Near;
            this.evaluatorResultPableCaption.CaptionTextColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.evaluatorResultPableCaption.Controls.Add(this.linkEvaluate);
            this.evaluatorResultPableCaption.Dock = System.Windows.Forms.DockStyle.Top;
            this.evaluatorResultPableCaption.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold);
            this.evaluatorResultPableCaption.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.evaluatorResultPableCaption.GradientEnd = System.Drawing.SystemColors.InactiveCaption;
            this.evaluatorResultPableCaption.GradientStart = System.Drawing.SystemColors.GradientInactiveCaption;
            this.evaluatorResultPableCaption.Location = new System.Drawing.Point(0, 0);
            this.evaluatorResultPableCaption.Name = "evaluatorResultPableCaption";
            this.evaluatorResultPableCaption.PanelIcon = null;
            this.evaluatorResultPableCaption.ShowBorder = true;
            this.evaluatorResultPableCaption.ShowIcon = false;
            this.evaluatorResultPableCaption.Size = new System.Drawing.Size(510, 21);
            this.evaluatorResultPableCaption.TabIndex = 0;
            this.evaluatorResultPableCaption.TextAntiAlias = true;
            // 
            // linkEvaluate
            // 
            this.linkEvaluate.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.linkEvaluate.AutoSize = true;
            this.linkEvaluate.BackColor = System.Drawing.Color.Transparent;
            this.linkEvaluate.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.linkEvaluate.LinkBehavior = System.Windows.Forms.LinkBehavior.AlwaysUnderline;
            this.linkEvaluate.LinkColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.linkEvaluate.Location = new System.Drawing.Point(461, 4);
            this.linkEvaluate.Name = "linkEvaluate";
            this.linkEvaluate.Size = new System.Drawing.Size(49, 13);
            this.linkEvaluate.TabIndex = 1;
            this.linkEvaluate.TabStop = true;
            this.linkEvaluate.Text = "E&valuate";
            this.linkEvaluate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.linkEvaluate.VisitedLinkColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.linkEvaluate.Click += new System.EventHandler(this.LinkEvaluate_Click);
            // 
            // expressionEditorViewEditorPanel
            // 
            this.expressionEditorViewEditorPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.expressionEditorViewEditorPanel.Location = new System.Drawing.Point(0, 0);
            this.expressionEditorViewEditorPanel.Name = "expressionEditorViewEditorPanel";
            this.expressionEditorViewEditorPanel.Size = new System.Drawing.Size(510, 409);
            this.expressionEditorViewEditorPanel.TabIndex = 1;
            // 
            // descriptionPanel
            // 
            this.descriptionPanel.BorderColor = System.Drawing.SystemColors.ControlDark;
            this.descriptionPanel.BorderWidth = 1;
            this.descriptionPanel.Caption = false;
            this.descriptionPanel.CaptionBeginColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(225)))), ((int)(((byte)(155)))));
            this.descriptionPanel.CaptionEndColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(78)))));
            this.descriptionPanel.CaptionGradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.descriptionPanel.CaptionHeight = 24;
            this.descriptionPanel.CaptionText = "Panel";
            this.descriptionPanel.CaptionTextAlignment = System.Drawing.StringAlignment.Near;
            this.descriptionPanel.CaptionTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.descriptionPanel.Controls.Add(this.labelHelpText);
            this.descriptionPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.descriptionPanel.Font = new System.Drawing.Font("Tahoma", 8F);
            this.descriptionPanel.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.descriptionPanel.GradientEnd = System.Drawing.SystemColors.Control;
            this.descriptionPanel.GradientStart = System.Drawing.SystemColors.Control;
            this.descriptionPanel.Location = new System.Drawing.Point(0, 0);
            this.descriptionPanel.Name = "descriptionPanel";
            this.descriptionPanel.Padding = new System.Windows.Forms.Padding(2, 4, 2, 2);
            this.descriptionPanel.PanelIcon = null;
            this.descriptionPanel.ShowBorder = true;
            this.descriptionPanel.ShowIcon = false;
            this.descriptionPanel.Size = new System.Drawing.Size(747, 44);
            this.descriptionPanel.TabIndex = 0;
            this.descriptionPanel.TextAntiAlias = true;
            // 
            // labelHelpText
            // 
            this.labelHelpText.AutoEllipsis = true;
            this.labelHelpText.BackColor = System.Drawing.SystemColors.Control;
            this.labelHelpText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.labelHelpText.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.labelHelpText.Location = new System.Drawing.Point(2, 4);
            this.labelHelpText.Name = "labelHelpText";
            this.labelHelpText.Padding = new System.Windows.Forms.Padding(2);
            this.labelHelpText.Size = new System.Drawing.Size(743, 38);
            this.labelHelpText.TabIndex = 2;
            // 
            // panelTopMargin
            // 
            this.panelTopMargin.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTopMargin.Location = new System.Drawing.Point(0, 0);
            this.panelTopMargin.Name = "panelTopMargin";
            this.panelTopMargin.Size = new System.Drawing.Size(747, 4);
            this.panelTopMargin.TabIndex = 13;
            // 
            // ExpressionEditorView
            // 
            this.Controls.Add(this.splitContainerMain);
            this.Controls.Add(this.panelTopMargin);
            this.MinimumSize = new System.Drawing.Size(338, 121);
            this.Name = "ExpressionEditorView";
            this.Size = new System.Drawing.Size(747, 461);
            this.Load += new System.EventHandler(this.ExpressionEditor_Load);
            this.contextMenuStripVariablesFunctions.ResumeLayout(false);
            this.splitContainerMain.Panel1.ResumeLayout(false);
            this.splitContainerMain.Panel2.ResumeLayout(false);
            this.splitContainerMain.ResumeLayout(false);
            this.splitContainerFunctionExpressions.Panel1.ResumeLayout(false);
            this.splitContainerFunctionExpressions.Panel2.ResumeLayout(false);
            this.splitContainerFunctionExpressions.ResumeLayout(false);
            this.splitContainerExpressionResult.Panel1.ResumeLayout(false);
            this.splitContainerExpressionResult.Panel2.ResumeLayout(false);
            this.splitContainerExpressionResult.ResumeLayout(false);
            this.richTxtExpressionBorderPanel.ResumeLayout(false);
            this.contextMenuStripTextPanes.ResumeLayout(false);
            this.richTextResultBorderPanel.ResumeLayout(false);
            this.evaluatorResultPableCaption.ResumeLayout(false);
            this.evaluatorResultPableCaption.PerformLayout();
            this.descriptionPanel.ResumeLayout(false);
            this.ResumeLayout(false);

		}

        #endregion

        private System.Windows.Forms.ImageList imageListIcons;
        private RichPanel richTxtExpressionBorderPanel;
        private RichPanel borderedPanelExpressionCaption;
        private System.Windows.Forms.RichTextBox richTextResult;
        private RichPanel evaluatorResultPableCaption;
        private System.Windows.Forms.LinkLabel linkEvaluate;
        private RichPanel descriptionPanel;
        private System.Windows.Forms.Label labelHelpText;
        private System.Windows.Forms.ToolTip toolTip;
        private System.Windows.Forms.ContextMenuStrip contextMenuStripVariablesFunctions;
        private System.Windows.Forms.ToolStripMenuItem addVariableToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem deleteVariableToolStripMenuItem;

//        private System.Windows.Forms.SaveFileDialog saveFileDialog;
        private System.Windows.Forms.ToolStripMenuItem editVariableToolStripMenuItem;
        private System.Windows.Forms.SplitContainer splitContainerMain;
        private System.Windows.Forms.SplitContainer splitContainerFunctionExpressions;
        private System.Windows.Forms.SplitContainer splitContainerExpressionResult;
        private System.Windows.Forms.TreeView treeViewVariablesFunctions;
        private RichPanel richPanelFunctionsCaption;
        private System.Windows.Forms.Panel panelTopMargin;
        internal System.Windows.Forms.RichTextBox ExpressionTextBox;
        private RichPanel richTextResultBorderPanel;
        private ExpressionFunctionsEditor expressionEditorViewEditorPanel;
        private System.Windows.Forms.ContextMenuStrip contextMenuStripTextPanes;
        private System.Windows.Forms.ToolStripMenuItem undoToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem redoToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparatorUndo;
        private System.Windows.Forms.ToolStripMenuItem cutToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem copyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem pasteToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparatorTextEdit;
        private System.Windows.Forms.ToolStripMenuItem selectAllToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparatorEditFunctions;
        private System.Windows.Forms.ToolStripMenuItem editFunctionsToolStripMenuItem;
    }
}
