// <auto-generated/>

namespace Konesans.Dts.ExpressionEditor.Controls
{
    /// <summary>
    /// Simple 3D line class
    /// </summary>
    partial class Line3D
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lblLine = new System.Windows.Forms.Label();
            this.SuspendLayout();
// 
// lblLine
// 
            this.lblLine.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.lblLine.BackColor = System.Drawing.SystemColors.ControlDark;
            this.lblLine.ForeColor = System.Drawing.SystemColors.ControlDark;
            this.lblLine.Location = new System.Drawing.Point(0, 0);
            this.lblLine.MaximumSize = new System.Drawing.Size(12400, 1);
            this.lblLine.MinimumSize = new System.Drawing.Size(1, 1);
            this.lblLine.Name = "lblLine";
            this.lblLine.Size = new System.Drawing.Size(30, 1);
            this.lblLine.TabIndex = 0;
            this.lblLine.Text = "label1";
// 
// Line3D
// 
            this.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.Controls.Add(this.lblLine);
            this.MaximumSize = new System.Drawing.Size(12400, 2);
            this.MinimumSize = new System.Drawing.Size(4, 2);
            this.Name = "Line3D";
            this.Size = new System.Drawing.Size(32, 2);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Label lblLine;
    }
}
